language: python

python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

# Specify branches to build
branches:
  only:
    - test

# command to run tests
script: pytest test_units.py
